"""empty message

Revision ID: 5a6c458adfcb
Revises: 3c616566b827
Create Date: 2023-03-08 10:44:25.101212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a6c458adfcb'
down_revision = '3c616566b827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rooms', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('baths', sa.String(length=80), nullable=True))
        batch_op.drop_column('num_of_rooms')
        batch_op.drop_column('num_of_bath')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_of_bath', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('num_of_rooms', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.drop_column('baths')
        batch_op.drop_column('rooms')

    # ### end Alembic commands ###
